"""add_missing_order_columns

Revision ID: f7145941af84
Revises: 045d7af72e16
Create Date: 2026-03-07 17:56:29.689638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7145941af84'
down_revision: Union[str, None] = '045d7af72e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the paymentstatus enum type first
    paymentstatus = sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus')
    paymentstatus.create(op.get_bind(), checkfirst=True)

    op.add_column('orders', sa.Column('payment_transaction_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))

    # Cast existing VARCHAR values to the new enum type using USING clause
    op.execute("ALTER TABLE orders ALTER COLUMN payment_status TYPE paymentstatus USING payment_status::paymentstatus")
    op.execute("ALTER TABLE orders ALTER COLUMN payment_status SET NOT NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'payment_transaction_id')
    # ### end Alembic commands ###
