worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # 1. API Reverse Proxy (api.1line.az)
    server {
        listen 80;
        server_name api.1line.az;

        location / {
            proxy_pass http://backend:8000; # Points to inside Docker network
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # 2. Frontend / Storefronts (*.1line.az)
    server {
        listen 80;
        server_name 1line.az *.1line.az;

        location / {
            proxy_pass http://frontend:80; # Points to Frontend static container
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
